ALTER TABLE sessions ADD COLUMN tokens_in INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sessions ADD COLUMN tokens_out INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sessions ADD COLUMN tokens_cache_read INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sessions ADD COLUMN tokens_cache_create INTEGER NOT NULL DEFAULT 0;
